### ISSUE TITLE
한글 검색이 동작하지 않음

### ISSUE THREAD

**Issue by BBBOMi** [Nexters/team-builder-web#51]

**Comment by inhyuck** [comment]
:sad

**Comment by inhyuck** [comment]
그러나 할 수 있다

**Comment by BBBOMi** [comment]
ㅋㅋㅋㅋㅋ해야지...
해내겠습니다🙆‍♀️🙆‍♂️🙆‍♀️🙆‍♂️

**Comment by BBBOMi** [comment]
ㅋㅋㅋㅋ해야지,,,
해내겠습니다!👊👊

**Comment by BBBOMi** [comment]
#### 해결했습니다
커밋 인덱스: [75b5e48](https://github.com/Nexters/team-builder-web/commit/75b5e48be24b40fbd59461ce63c0378007703d5e)

**Comment by BBBOMi** [comment]
#### 해결했습니다
커밋 인덱스: [75b5e48](https://github.com/Nexters/team-builder-web/commit/75b5e48be24b40fbd59461ce63c0378007703d5e)
